
- name: Install snap core
  community.general.snap:
    name: core


- name: Install certbot
  community.general.snap:
    name: certbot
    classic: yes
 
- name: Prepare the Certbot command
  file:
    src: "/snap/bin/certbot" 
    dest: "/usr/bin/certbot"
    state: "link"

- name: Get and install certificates
  command: "certbot --apache -d {{ domain }},www.{{ domain }} --agree-tos -m {{ admin_email }} "

- name: Test automatic certificate renewal
  command: certbot renew --dry-run

